cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import path
from catalog import views

app_name = 'catalog'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

r_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),

]

catalog/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, null=True)
    description = models.TextField()
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name', '-created_at')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_detail', args=[self.id, self.slug])

catalog/views.py
from django.shortcuts import render, get_object_or_404
from catalog.models import Product, Category
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm

def product_list(request):
    """
    Вывод всего каталога
    """
    products = Product.objects.filter(available=True).order_by('name')
    return render(request, 'product/list.html', context={'products': products})



def product_detail(request, id, slug):
    """
    Вывод отдельного товара
    """
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_add_product_form = CartAddProductForm()
    return render(request, 'product/detail.html',
                  context={'product': product,
                           'cart_add_product_form': cart_add_product_form})

catalog/templates/product/detail.html
{% extends "base.html" %}

{% block title %}{{ product.name }}{% endblock %}


{% block content %}
    <div>
    <h1>{{ product.name }}</h1>
        <hr>
    <p>
        {{ product.description }}
    </p>
    <p>
        <b>{{ product.price }} руб</b>
    </p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_add_product_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
    </form>
</div>
{% endblock %}

catalog/templates/product/list.html
{% extends "base.html" %}

{% block title %}Каталог товаров{% endblock %}


{% block content %}
    <div>
    {%  if user.is_authenticated %}
        <p>Привет, {{ user.username }}!</p>
    {% endif %}
    </div>
    {% for product in products %}
    <div>
        <a href="{{ product.get_absolute_url }}"><h1>{{ product.name }}</h1></a>
        <p>{{ product.price }}</p>
    </div>
{% endfor %}

{% endblock %}