cart/urls.py
from django.urls import path
from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

r_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("orders/", include("orders.urls")),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

CHOICES = [(i, str(i)) for i in range(1, 6)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=CHOICES, coerce=int)
    override = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from cart.cart import Cart
from cart.forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Корзина</title>
</head>
<body>
<h1>Корзина</h1>
<hr>
<table>
    <thead>
        <tr>
            <th>Продукт</th>
            <th>Кол-во</th>
            <th>Цена за штуку</th>
            <th>Cтоимость</th>
        </tr>
    </thead>
<tbody>
{% for item in cart %}
{% with product=item.product %}
<tr>
    <td>{{ product.name }}</td>
    <td>{{ item.quantity }}</td>
    <td>{{ item.price }} $</td>
    <td>{{ item.total_price }} $</td>
    <td>
        <form action="{% url "cart:cart_remove" product.id %}" method="post">
            <input type="submit" value="Удалить">
            {% csrf_token %}
        </form>
    </td>
</tr>
{% endwith %}
{% endfor %}
<tr>
    <td colspan="5">{{ cart.get_total_price }}</td>
</tr>
</tbody>
</table>
</body>
</html>